# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamid', models.AutoField(db_column='TeamID', primary_key=True, serialize=False)),
                ('team_name', models.CharField(db_column='TeamName', max_length=50)),
            ],
            options={
                'verbose_name': 'Team',
                'ordering': ('team_name',),
                'db_table': 'Team',
                'verbose_name_plural': 'Teams',
                'managed': True,
            },
        ),
    ]
