# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev_metrics', '0002_reportingperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityMeasure',
            fields=[
                ('capacity_measure_id', models.AutoField(db_column='CapacityMeasureID', primary_key=True, serialize=False)),
                ('team_capacity_in_hours', models.DecimalField(db_column='TeamCapacityInHours', decimal_places=2, max_digits=5)),
                ('team_velocity_in_story_points', models.DecimalField(db_column='TeamVelocityInStoryPoints', decimal_places=2, max_digits=5)),
                ('team_FTE', models.DecimalField(db_column='TeamFTE', decimal_places=1, max_digits=5)),
                ('reporting_period', models.ForeignKey(db_column='ReportingPeriodID', on_delete=django.db.models.deletion.DO_NOTHING, to='dev_metrics.ReportingPeriod')),
                ('team', models.ForeignKey(db_column='TeamID', on_delete=django.db.models.deletion.DO_NOTHING, to='dev_metrics.Team')),
            ],
            options={
                'verbose_name_plural': 'Capacity Measures',
                'managed': True,
                'verbose_name': 'Capacity Measure',
                'db_table': 'CapacityMeasure',
                'ordering': ('team__team_name', 'reporting_period__end_date'),
            },
        ),
    ]
